[package]
name = "dagdb"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Distributed DAG transaction store on top of Raft"
repository = "https://github.com/yatledger/srv"

[dependencies]
axum = "0.7" # Фреймворк для создания HTTP-сервера.
num_cpus = "1.17.0"
openraft = { git = "https://github.com/databendlabs/openraft", rev = "54ffb00", features = ["serde", "type-alias"] }
rayon = "1.10.0"
redis = { version = "0.32.0", features = ["tokio-comp", "connection-manager"] }
serde = { version = "1.0", features = ["derive"] } # Для сериализации/десериализации JSON.
serde_json = "1.0" # Для работы с JSON в graph.rs.
tokio = { version = "1.0", features = ["full"] } # Асинхронный runtime.
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "fmt", "chrono"] }
reqwest = { version = "0.12.20", features = ["json"] }
axum-macros = "0.5.0"
clap = { version = "4.5.40", features = ["derive", "env"] }
dotenvy = "0.15"
ed25519-dalek = "2.1.1"
base58 = "0.2.0"
hex = "0.4.3"
blake3 = "1.8.2"
redb = "2.6.4"
thiserror = "2.0"
#anyhow = "1.0.98" кастомные ошибки
